# Generated by Django 5.1.2 on 2024-10-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productid',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
